from dataclasses import replace
import json
from pathlib import Path

import numpy as np
import pytest

from bayesian_rrtl.diagnostics import chain_diagnostics, posterior_diagnostics
from bayesian_rrtl.ensemble import BARTRegressor
from bayesian_rrtl.priors import NoisePrior, TreePrior
from test_bayesian_kernel import tiny_data


def test_iid_chains_and_correlated_ar1_ess():
    rng = np.random.default_rng(3)
    iid = rng.normal(size=(4, 10000))
    result = chain_diagnostics(iid)
    assert result['rhat'] < 1.01
    assert 32000 < result['ess_bulk'] <= 40000
    assert result['ess_tail'] > 30000
    phi = 0.8
    innovations = rng.normal(size=(4, 12000))
    ar = innovations.copy()
    for t in range(1, ar.shape[1]):
        ar[:, t] = phi * ar[:, t-1] + innovations[:, t]
    result = chain_diagnostics(ar[:, 2000:])
    theoretical = 40000 * (1-phi) / (1+phi)
    assert 0.65 * theoretical < result['ess_bulk'] < 1.35 * theoretical
    assert result['rhat'] < 1.01


def test_location_scale_and_drift_failures_are_detected():
    samples = np.random.default_rng(9).normal(size=(4, 2000))
    shifted = samples + np.arange(4)[:, None] * 3
    assert chain_diagnostics(shifted)['rhat'] > 1.1
    scaled = samples * np.array([1, 1, 8, 8])[:, None]
    assert chain_diagnostics(scaled)['rhat'] > 1.1
    drift = samples + np.linspace(-5, 5, 2000)
    assert chain_diagnostics(drift)['rhat'] > 1.1


def test_constant_stuck_ties_and_invalid_inputs():
    assert chain_diagnostics(np.ones((4, 20)))['status'] == 'constant'
    result = chain_diagnostics(np.repeat(np.arange(4)[:, None], 20, axis=1))
    assert result['status'] == 'stuck' and result['ess_bulk'] == 0
    result = chain_diagnostics(np.random.default_rng(4).integers(0, 5, size=(4, 1001)))
    assert result['status'] == 'ok' and result['draws_used'] == 4000
    for invalid in [np.zeros((1, 20)), np.zeros((4, 3)), np.full((4, 20), np.nan)]:
        with pytest.raises(ValueError):
            chain_diagnostics(invalid)


def test_posterior_diagnostics_require_same_fixed_problem():
    batch, y, _ = tiny_data()
    model = BARTRegressor(m=2, tree_prior=TreePrior(max_depth=1))
    chains = [model.fit(batch, y, np.random.default_rng(seed), burn_in=10, draws=100) for seed in [1, 2]]
    result = posterior_diagnostics(chains, batch)
    assert set(result) == {'prediction_0', 'prediction_1', 'prediction_2', 'sigma2', 'total_leaves', 'max_depth'}
    assert all('rhat' in value for value in result.values())
    for invalid in [replace(chains[1], data_hash='other'), replace(chains[1], noise_prior=NoisePrior(lambda_=1))]:
        with pytest.raises(ValueError, match='Incompatible'):
            posterior_diagnostics([chains[0], invalid], batch)


def test_diagnostics_against_independent_arviz_reference():
    # Stored values were generated by ArviZ 0.21.0 in an isolated temporary
    # installation. ArviZ is not a runtime or test dependency of this project.
    reference = json.loads((Path(__file__).resolve().parents[1] /
                            'docs/diagnostics_reference_h3.json').read_text())
    rng = np.random.default_rng(reference['seed'])
    iid = rng.normal(size=(4, 1000))
    ar = iid.copy()
    for t in range(1, 1000):
        ar[:, t] = 0.8 * ar[:, t-1] + iid[:, t]
    cases = {'iid': iid, 'ar1': ar, 'shifted': iid + np.arange(4)[:, None],
             'scaled': iid * np.array([1, 1, 8, 8])[:, None],
             'discrete': rng.integers(0, 5, size=(4, 1000))}
    for name, values in cases.items():
        expected = reference['cases'][name]['expected']
        actual = chain_diagnostics(values)
        assert actual['rhat'] == pytest.approx(expected['rhat'], abs=1e-12)
        for field in ('ess_bulk', 'ess_tail'):
            # Conservative cap and finite-lag truncation are documented.
            assert actual[field] == pytest.approx(min(values.size, expected[field]), rel=0.01)
